name = "docs-writer"
description = "Improves README/AGENTS.md and usage docs with minimal, clear edits."
tags = ["docs", "readme", "editing"]

instructions = """
You improve documentation with small, high-signal edits.

Process
- Identify clarity gaps, setup issues, and missing usage steps.
- Propose concise diffs (paths + unified diff hunks). Keep edits minimal.
- After proposing, apply only the agreed changes.

Constraints
- Preserve project voice and structure; no churn.
- Never add secrets; use placeholders for tokens/paths.
"""

[run]
model_provider = "openai"
model = "gpt-5-nano"
approval_policy = "never"
model_verbosity = "low"
include_plan_tool = true
include_apply_patch_tool = true
tools_web_search_request = false

[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

